[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cli-bin"
path = "bin/main.rs"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
stump_core = { path = "../../core" }

tokio = { workspace = true }
thiserror = { workspace = true }
prisma-client-rust = { workspace = true }
dialoguer = "0.11.0"
indicatif = "0.17.7"

bcrypt = { workspace = true }
